name: Publish

on:
  push:
    branches:
      - main  # 仅在主分支推送时触发，您可以根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2  # 允许在 x86 上运行 ARM 容器

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false  # 设置为 false，因为我们不会推送到 Docker Hub
          tags: my-python-app:latest  # 自定义镜像名称

      - name: Run tests and build packages
        run: |
          docker run --rm --platform linux/arm/v7 \
            -v ${{ github.workspace }}:/app \
            -w /app \
            my-python-app:latest \
            /bin/bash -c "
              pip install --upgrade pip &&
              pip install -r requirements.txt &&
              python setup.py sdist bdist_wheel
            "

      - name: Publish to PyPI
        run: |
          docker run --rm --platform linux/arm/v7 \
            -v ${{ github.workspace }}:/app \
            -w /app \
            my-python-app:latest \
            /bin/bash -c "
              python -m twine upload --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*
            "

      - name: Upload built packages
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: dist/
