name: Publish

on:
  push:
    branches:
      - main  # 仅在主分支推送时触发，您可以根据需要修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and publish using Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false  # 设置为 false，如果您不想推送镜像
          tags: your-image-name:latest
          platforms: linux/arm/v7  # ARM32架构
          build-args: |
            PYTHON_VERSION=3.8

      - name: Publish to PyPI
        run: |
          docker run --rm --platform linux/arm/v7 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            python:3.8 \
            /bin/bash -c "
              pip install --upgrade pip &&
              pip install -r requirements.txt &&
              python setup.py sdist bdist_wheel &&
              python -m twine upload --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*
            "

      - name: Upload built packages
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: dist/
